---
title: "Geodex Spatial Search"
output:
  html_document:
    df_print: paged
---

```{r}
location <- c(-105.2705,40.015)
```

```{r}
#install.packages("geojson")
library(geojson)

point <- geojson::point(paste('{ "type": "Point", "coordinates": [', location[1], ',' , location[2], '] }'))
feature <- geojson::feature(point)
feature_collection <- geojson::featurecollection(feature)
feature_collection_str <- geo_pretty(feature_collection)
```

```{r}
search_type <- "spatial/search/object"
```

```{r}
domain_url <- "http://geodex.org/api/v1/"
request_url <- paste(domain_url, search_type, sep="")
```

```{r}
params_list <- list(geowithin = feature_collection_str)
```

```{r}
library(httr)
r <- GET(request_url, query = params_list)
results <- content(r, "text", encoding = "ISO-8859-1")
```

```{r}
library(rjson)
results_json <- fromJSON(results)
features <- results_json$features
number_of_results <- length(features)
first_result <- features[[1]]

url <- first_result$properties$URL
geometry <- first_result$geometry$type
coordinates <- first_result$geometry$coordinates[[1]]

print(paste("Number of Results =", number_of_results))
print(paste("URL of First Result =", url))
print(paste("Coordinates of First Result = ", coordinates))
```










