---
title: "Geodex Text Search"
output:
  html_document:
    df_print: paged
---

```{r}
text_search_value <- "carbon"
```

```{r}
number_of_results <- 100
```

```{r}
search_type <- "textindex/searchset"
```

```{r}
domain_url <- "http://geodex.org/api/v1/"
```

```{r}
request_url <- paste(domain_url, search_type, sep="")
```

```{r}
params_list <- list(q = text_search_value, s = 0, n = toString(number_of_results))
```

```{r}
library(httr)
r <- GET(request_url, query = params_list)
results <- content(r, "text", encoding = "ISO-8859-1")
```

```{r}
library(rjson)
results_json <- fromJSON(results)
for (i in c(1:length(results_json))){
  print(paste("Index =", results_json[[i]]$index))
  print(paste("High Score =", results_json[[i]]$highscore))
  print(paste("Number of Results =", length(results_json[[i]]$or)))
}
```
```{r}
for (i in c(1:length(results_json[[1]]$or))){
  print(paste("Position =", results_json[[1]]$or[[i]]$position))
  print(paste("Score =", results_json[[1]]$or[[i]]$score))
  print(paste("URL =", results_json[[1]]$or[[i]]$URL))
}
```

```{r}
search_type <- "textindex/search"
```

```{r}
domain_url <- "http://geodex.org/api/v1/"
```

```{r}
request_url <- paste(domain_url, search_type, sep="")
```

```{r}
params_list <- list(q = text_search_value, s = 0, n = toString(number_of_results))
```

```{r}
r <- GET(request_url, query = params_list)
results <- content(r, "text", encoding = "ISO-8859-1")
```

```{r}
results_json <- fromJSON(results)
for (i in c(1:length(results_json))){
  print(paste("Position =", results_json[[i]]$position))
  print(paste("Score =", results_json[[i]]$score))
  print(paste("URL =", results_json[[i]]$URL))
}
```

